name: Docker Build & Push

on:
  push:
    tags:
      - "*"
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:
    inputs:
      force:
        description: Build the image even if it already exists
        required: false
        default: false
        type: boolean

jobs:
  initialize:
    runs-on: ubuntu-latest
    outputs:
      TARGET_IMAGE_TAG: ${{ steps.radicale-version.outputs.release }}
      radicale_VERSION: ${{ steps.prepare.outputs.radicale-version }}
    steps:
      - name: Get latest Radicale version
        id: radicale-version
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          owner: Kozea
          repo: Radicale
          token: ${{ secrets.GITHUB_TOKEN }}
          excludes: prerelease, draft

      - name: Prepare
        id: prepare
        run: echo "radicale-version=$(echo "${{ steps.radicale-version.outputs.release }}"|awk '{print substr($0, 2)}')" >> $GITHUB_OUTPUT

  build:
    needs: initialize
    uses: aszili/github-actions/.github/workflows/build-docker-image.yml@main
    with:
      target_tag: ${{ needs.initialize.outputs.TARGET_IMAGE_TAG }}
      build_args: radicale_VERSION=${{ needs.initialize.outputs.radicale_VERSION }}
      force: ${{ contains(inputs.force, 'true') }}