name: Docker Build & Push

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      force:
        description: Build the image even if it already exists
        required: false
        default: false
        type: boolean

jobs:
  initialize:
    uses: aszili/github-actions/.github/workflows/prepare-package-version.yml@main
    with:
      package_name: radicale
      output_env_var: RADICALE_VERSION

  build:
    needs: initialize
    uses: aszili/github-actions/.github/workflows/build-docker-image.yml@main
    with:
      target_tag: ${{ needs.initialize.outputs.version }}
      build_args: RADICALE_VERSION=${{ needs.initialize.outputs.version }}
      force: ${{ contains(inputs.force, 'true') }}